### ISSUE TITLE
Update to current Asai

### ISSUE THREAD

**Issue by mikeshulman** [RedPRL/bantorra#77]
Bantorra appears to be using an outdated version of Asai, with Logger instead of Reporter.

**Comment by favonia** [comment]
I do have a in-progress local branch for this. I have been jumping between an on-going complete redesign and minor clean-ups (such as upgrading asai). Maybe I should finish minor tasks first given the long delay.

PS: While the current design of bantorra is okay, it's not great. In particular, I want to have a built-in Go-like minimum version resolution. I also want an "offline" mode to work without the internet. All of these would fundamentally change how the library works. Also we don't have a prototype with tons of (interdependent) user libraries, so the design hasn't really been "tested" yet.

**Comment by mikeshulman** [comment]
How much will the complete redesign change the user interface?

**Comment by favonia** [comment]
@mikeshulman I'm not sure, but I would not recommend trying out this library (bantorra) in a serious way now.

**Comment by mikeshulman** [comment]
Ok.
